### ISSUE TITLE
Execution hangs without any visible error

### ISSUE THREAD

**Issue by cristiammercado** [PavanMudigonda/jacoco-reporter#22]
**Describe the bug**
I have added this action today to see JaCoCo's coverage reports. Right now I'm using it for `feature/**` project branches, but the execution of the entire GitHub workflow hangs, especially in the part shown in the screenshot below.

The configuration of my action is very basic, it is a Maven project, I share it below:

```yaml
name: Feature CI

on:
  push:
    branches:
      - feature/**

env:
  MAVEN_OPTS: '-Dhttps.protocols=TLSv1.2 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true'
  MAVEN_CLI_OPTS: '--batch-mode --errors --fail-at-end --show-version'

jobs:
  deploy:
    name: Feature branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'maven'
      - name: Test and compile project
        run: |
          chmod +x ./mvnw
          ./mvnw $MAVEN_CLI_OPTS clean compile test package
      - name: Publish test coverage results
        uses: PavanMudigonda/jacoco-reporter@v4.5
        with:
          coverage_results_path: 'target/site/jacoco/jacoco.xml'
          coverage_report_title: 'Test coverage results'
          coverage_report_name: 'Test coverage results'
          github_token: ${{ secrets.GITHUB_TOKEN }}

```

**To Reproduce**
1. Create branch feature/any-test-here
2. Push to GitHub
3. Start workflow execution
4. Workflow never stops and does not finish executing the action

**Expected behavior**
It is expected to run normally, or if there is an error it will show it and end the workflow.

**Screenshots**
![Screenshot_6](https://user-images.githubusercontent.com/4806666/179782727-80e2e0d9-53a8-4b8a-a355-b284cc06f157.png)

**Desktop (please complete the following information):**
Not apply

**Smartphone (please complete the following information):**
Not apply

**Additional context**

**Comment by PavanMudigondaTR** [comment]
@cristiammercado Hi, thanks for trying to use my reporter. I tested it using Gradle only and haven't received any issues so far. I will test using Maven and see whats causing this. Ideally error should not come but if it comes it should be valid and meaningful one. I will get back to you in a day!

**Comment by cristiammercado** [comment]
I am using the Maven plugin dependency `jacoco-maven-plugin` version `0.8.8`. I already confirmed that the location of the file is correct (`target/site/jacoco/jacoco.xml`). I
attached the file for you to download and do the test, I don't know if the structure suddenly changed or something similar.

[jacoco.zip](https://github.com/PavanMudigonda/jacoco-reporter/files/9142865/jacoco.zip)

Thanks in advance!

**Comment by cristiammercado** [comment]
I'm attaching some screenshots of the folder structure where the JaCoCo file is located.

![image](https://user-images.githubusercontent.com/4806666/179799039-f8c32754-fe65-41e3-bff7-178c6e44eac7.png)

![image](https://user-images.githubusercontent.com/4806666/179799096-a9f83fbc-9cc4-44cb-9b50-e823b7ca0e50.png)

**Comment by PavanMudigonda** [comment]
@cristiammercado  Could you let me know if you got this error ? I got this error with the jacoco.xml file you provided yesterday. 
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/29324338/180067778-7fa37b4b-e086-4fc9-84be-65c75636f85c.png">

**Comment by PavanMudigonda** [comment]
@cristiammercado please try again with v4.8

**Comment by benediktarnold** [comment]
I get exactly the same error as you posted above using `jacoco-maven-plugin`. Even with v4.8

**Comment by PavanMudigondaTR** [comment]
> 

It seems this could be case when you have no missing lines and 100% coverage is achieved. I will try to fix it this week !

@benediktarnold @cristiammercado

**Comment by benediktarnold** [comment]
Even if I'd love this to be the reason, I can assure you that this is not the case for my codebase ;-) For some packages, we have 100% line coverage and no missed lines, but not overall.

**Comment by PavanMudigondaTR** [comment]
> Even if I'd love this to be the reason, I can assure you that this is not the case for my codebase ;-) For some packages, we have 100% line coverage and no missed lines, but not overall.

would you be able to give me a screenshot of your error ? is it exact same issue from above.

**Comment by benediktarnold** [comment]
Sure thing. This is my step configuration:
```
      - name: JaCoCo Code Coverage Report
        id: jacoco_reporter
        uses: PavanMudigonda/jacoco-reporter@v4.8
        with:
          coverage_results_path: jacoco.xml
          coverage_report_name: Coverage
          coverage_report_title: JaCoCo
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_check_run: false
          minimum_coverage: 50
          fail_below_threshold: true
          publish_only_summary: false
```
I added a debug step before the reporter, to show that the jacoco.xml is there.
<img width="1004" alt="Bildschirm­foto 2023-01-25 um 17 03 43" src="https://user-images.githubusercontent.com/178772/214620152-1f976961-252a-4106-a3df-8754e2ef38a0.png">
