### ISSUE TITLE
Action Fails With "Resource not accessible by integration"

### ISSUE THREAD

**Issue by suniastar** [PavanMudigonda/jacoco-reporter#25]
**Describe the bug**
When the action is run in a pull request by dependabot or a forked repo (e.g. when bumping up a version in a pull request) this step will fail with the default github token `${{ secrets.GITHUB_TOKEN }}` due to a lack of permissions.

**Error Log**
```
##[group]Run PavanMudigonda/jacoco-reporter@v4.6
with:
  coverage_results_path: target/site/jacoco/jacoco.xml
  coverage_report_name: Coverage
  coverage_report_title: JaCoCo
  github_token: ***
  skip_check_run: false
  minimum_coverage: 80
  fail_below_threshold: true
  publish_only_summary: false
env:
  JAVA_HOME: /opt/hostedtoolcache/Java_Zulu_jdk/17.0.4-8/x64
  JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Zulu_jdk/17.0.4-8/x64
##[endgroup]
[command]/usr/bin/pwsh -f /home/runner/work/_actions/PavanMudigonda/jacoco-reporter/v4.6/action.ps1
Module [GitHubActions] not found, INSTALLING...
Running from [/home/runner/work/_actions/PavanMudigonda/jacoco-reporter/v4.6]

Creating test results space

/home/runner/work/ms-address/ms-address/_TMP

Publishing Report to GH Workflow

Building human-readable code-coverage report

VERBOSE: Resolving XML file relative to current directory: /home/runner/work/ms-address/ms-address/target/site/jacoco/jacoco.xml
VERBOSE: Resolving default XSL file: /home/runner/work/_actions/PavanMudigonda/jacoco-reporter/v4.6/jacoco-report/jacocoxml2md.xsl
VERBOSE: Loaded XSL transformer
VERBOSE: Transforming XML to MD
Publishing Report to GH Workflow

Resolving REF 

Resolving PR REF

Resolved REF as 60b3899ccde75d92444458b181f8e69bbb46bdd0

Resolve Repo Full Name as suniastar/ms-address

Adding Check Run

Invoke-WebRequest: /home/runner/work/_actions/PavanMudigonda/jacoco-reporter/v4.6/action.ps1:165
Line |
 165 |      Invoke-WebRequest -Headers $hdr $url -Method Post -Body ($bdy | C …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | {"message":"Resource not accessible by
     | integration","documentation_url":"https://docs.github.com/rest/reference/checks#create-a-check-run"}

##[error]The process '/usr/bin/pwsh' failed with exit code 1

```

**To Reproduce**
1. Create a workflow with this github action according to the readme (sample below)
2. Let in run in a pull request by dependabot or a forked repo

**Expected behavior**
The action should not fail and append the report to the check

**Workflow file**
```yaml
name: Pull Requests Checks

on:
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Set up Java JDK
        uses: actions/setup-java@v3.5.0
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots test
      - name: JaCoCo Code Coverage Report
        uses: PavanMudigonda/jacoco-reporter@v4.6
        with:
          coverage_results_path: target/site/jacoco/jacoco.xml
          coverage_report_name: Coverage
          coverage_report_title: JaCoCo
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_check_run: false
          minimum_coverage: 80
          fail_below_threshold: true
          publish_only_summary: false

```

**Possible fix**
The workflow needs `check: write` permissions.
```yaml
permissions:
  checks: write
```
