### ISSUE TITLE
Some errors appearing on action execution (not happening before)

### ISSUE THREAD

**Issue by tino-fernandez** [PavanMudigonda/jacoco-reporter#29]
**Describe the bug**
Getting some errors from last week, was working before and no action inputs were modified. Error shows as:

```
Error: Unable to process file command 'output' successfully.
Error: Invalid format '# Coverage Report: JaCoCo'
```

**To Reproduce**

INPUTS
```
Run PavanMudigonda/jacoco-reporter@v4.6
  with:
    coverage_results_path: front-api/build/coverage/test/jacocoTestReport.xml
    coverage_report_name: Coverage
    coverage_report_title: JaCoCo
    github_token: ***
    skip_check_run: true
    minimum_coverage: 50
    fail_below_threshold: true
    publish_only_summary: false
  env:
    TOKEN: ***
    GH_TOKEN: ***
    CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE: /home/runner/work/infrastructure/infrastructure/gha-creds-dba5d7e06905db04.json
    GOOGLE_APPLICATION_CREDENTIALS: /home/runner/work/infrastructure/infrastructure/gha-creds-dba5d7e06905db04.json
    GOOGLE_GHA_CREDS_PATH: /home/runner/work/infrastructure/infrastructure/gha-creds-dba5d7e06905db04.json
    CLOUDSDK_CORE_PROJECT: morgan-abx
    CLOUDSDK_PROJECT: morgan-abx
    GCLOUD_PROJECT: morgan-abx
    GCP_PROJECT: morgan-abx
    GOOGLE_CLOUD_PROJECT: morgan-abx
    CLOUDSDK_METRICS_ENVIRONMENT: github-actions-setup-gcloud
    JAVA_HOME: /opt/hostedtoolcache/Java_Zulu_jdk/17.0.5-8/x64
    JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Zulu_jdk/17.0.5-8/x64
```

Complete log output:
```
/usr/bin/pwsh -f /home/runner/work/_actions/PavanMudigonda/jacoco-reporter/v4.6/action.ps1
Module [GitHubActions] not found, INSTALLING...
Running from [/home/runner/work/_actions/PavanMudigonda/jacoco-reporter/v4.6]

Creating test results space

/home/runner/work/infrastructure/infrastructure/_TMP

Publishing Report to GH Workflow

Building human-readable code-coverage report

VERBOSE: Resolving XML file relative to current directory: /home/runner/work/infrastructure/infrastructure/front-api/build/coverage/test/jacocoTestReport.xml
VERBOSE: Resolving default XSL file: /home/runner/work/_actions/PavanMudigonda/jacoco-reporter/v4.6/jacoco-report/jacocoxml2md.xsl
VERBOSE: Loaded XSL transformer
VERBOSE: Transforming XML to MD
Building human-readable code-coverage report

VERBOSE: Resolving XML file relative to current directory: /home/runner/work/infrastructure/infrastructure/front-api/build/coverage/test/jacocoTestReport.xml
VERBOSE: Resolving default XSL file: /home/runner/work/_actions/PavanMudigonda/jacoco-reporter/v4.6/jacoco-report/buildsummary2md.xsl
VERBOSE: Loaded XSL transformer
VERBOSE: Transforming XML to MD
Covered Lines: 6204
Missed Lines: 1785
Total Lines: 7989
Coverage: 77.66
  * fail_below_threshold: true

Error: Unable to process file command 'output' successfully.
Error: Invalid format '# Coverage Report: JaCoCo'
```

**Screenshot**

<img width="1137" alt="Screen Shot 2022-11-14 at 09 31 50" src="https://user-images.githubusercontent.com/101345155/201612526-3af0d427-1f75-4cad-ae2d-a9a2870b7512.png">

**Expected behavior**
Action executes without errors.

**Additional context**
Github hosted Linux agents
