### ISSUE TITLE
Unable to locate executable file: pwsh on Self-hosted GitHub Runner

### ISSUE THREAD

**Issue by dmytro-orlenko** [PavanMudigonda/jacoco-reporter#55]
**Describe the bug**
Error: Unable to locate executable file: pwsh. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.

I've used Self-Hosted Github Runner on my own Kubernetes Cluster (1.28)
Runner work on image - summerwind/actions-runner-dind:v2.311.0-ubuntu-20.04

```
    - name: Publish Test Coverage Report
      id: jacoco_report
      uses: PavanMudigonda/jacoco-reporter@v4.9
      with:
        coverage_results_path: ${{ github.workspace }}/build/jacoco.xml
        coverage_report_name: Coverage
        coverage_report_title: JaCoCo
        github_token: ${{ secrets.GITHUB_TOKEN }}
        skip_check_run: false
        minimum_coverage: 80
        fail_below_threshold: false
        publish_only_summary: false
```
