### ISSUE TITLE
Can't get coverageSummary from outputs

### ISSUE THREAD

**Issue by 9b9** [PavanMudigonda/jacoco-reporter#56]
**Describe the bug**
When I echo the outputs.coverageSummary, nothing is printed. I noticed that the variable is marked. Does it still work?

**To Reproduce**

**Expected behavior**
Get the core coverage summary from outputs variable.

By the way, there is one less white space in the sample code:
```yaml
     # ...
# ↓ 6 spaces
      - name: JaCoCo Code Coverage Report
         ...

# ↓ 5 spaces
     - name: Add Coverage Job Summary
       ...
```
And the GitHub will throw an error about yaml syntax:

Invalid workflow file: .github/workflows/java-pipeline.yml#L18
You have an error in your yaml syntax on line 18
