### ISSUE TITLE
Regression: build failure when upgrading from v4.9 to v5.0

### ISSUE THREAD

**Issue by opwvhk** [PavanMudigonda/jacoco-reporter#59]
**Regression Summary**

The GitHub Action below works with v4.9, but fails with v5.0.

The action:
```
name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Publish Test Coverage Results
        # noinspection SpellCheckingInspection
        uses: PavanMudigonda/jacoco-reporter@v5.0
        with:
          coverage_results_path: 'target/site/jacoco/jacoco.xml'
          coverage_report_title: 'Test Coverage Results'
          coverage_report_name: 'Test-Coverage-Results'
          github_token: ${{ secrets.GITHUB_TOKEN }}
```

The error:
```
Error: Unable to process file command 'output' successfully.
Error: Invalid format '# Coverage Report: Test Coverage Results'
```

With v4.9, the build successfully publishes the code coverage results.
